### ISSUE TITLE
[BUG]-Router switcher polling is not working

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-biamp-tesira#84]
**Describe the bug**
Triggers for manual polling are not sending 'get input X' commands
Commands for interval polling based on pollIntervalMs config value are not sending

**Stacktrace**
N/A

**To Reproduce**
Steps to reproduce the Manual Polling behavior:
1. Load EFS and SIMPL program
2. Track commands sent to Tesira from EFS
3. Trigger Poll from SIMPL
4. See how no command sent when poll requested

**Expected behavior**
Poll commands to send at regular intervals and for manual polling to send 'get' command on demand

**Comment by cdenig** [comment]
@TrevorPayne /tree/hotfix/switcher-router-polling is work in progress.  But I'm not sure how to fix the interval polling and could use some help

**Comment by TrevorPayne** [comment]
@cdenig - check out line 97 in `TesiraDspSwitcher.cs`

You're testing the value of something that doesn't get set until the Initialize() method.

Either remove the conditional and build the poll timer ALWAYS (since you have a conditional statement for actually giving it poll values) - or move it into initialize after `Type` is set.
